[package]
name = "nopsled_analyzer"
version = "0.1.0"
authors = ["Matt Miller <mmiller@hick.org>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
hex = "0.4.2"
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["full"] }
redis = "0.16.0"
async-std = "1.6.1"